import { StyleSheet } from 'react-native';
import { borderRadius, colors, shadows, spacing, typography } from '@/lib/theme';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...shadows.md,
  },
  videoLayer: {
    flex: 1,
  },
  video: {
    width: '100%',
    height: '100%',
    backgroundColor: '#040608',
  },
  posterOverlay: {
    ...StyleSheet.absoluteFillObject,
    width: undefined,
    height: undefined,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 12, 16, 0.58)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  loadingCard: {
    width: '100%',
    maxWidth: 260,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#0E141A',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    alignItems: 'center',
    gap: spacing.sm,
  },
  waitingBars: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    height: 28,
  },
  waitingBar: {
    width: 6,
    height: 22,
    borderRadius: 999,
    backgroundColor: colors.primary.DEFAULT,
  },
  loadingLabel: {
    color: colors.text.inverse,
    fontFamily: typography.fontFamily.body,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
  },
  errorCard: {
    width: '100%',
    maxWidth: 280,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.error,
    backgroundColor: '#2E1212',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
    alignItems: 'center',
    gap: spacing.xs,
  },
  errorTitle: {
    color: colors.text.inverse,
    fontFamily: typography.fontFamily.body,
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold,
  },
  errorBody: {
    color: '#F4C3C3',
    fontFamily: typography.fontFamily.body,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: spacing.sm,
    minHeight: 34,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.error,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryLabel: {
    color: colors.text.inverse,
    fontFamily: typography.fontFamily.body,
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
  },
  centeredState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  controlsOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(6, 8, 12, 0.16)',
    padding: spacing.sm,
    gap: spacing.sm,
  },
  centerControls: {
    position: 'absolute',
    left: spacing.sm,
    right: spacing.sm,
    top: '50%',
    marginTop: -28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  playButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: 'rgba(12, 18, 24, 0.65)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playButtonPaused: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(8, 14, 20, 0.75)',
  },
  seekButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(8, 12, 16, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  timeLabel: {
    width: 44,
    color: colors.text.inverse,
    fontFamily: typography.fontFamily.mono,
    fontSize: typography.fontSize.xs,
    textAlign: 'center',
  },
  progressTrack: {
    flex: 1,
    height: 12,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center',
  },
  progressFill: {
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.primary.DEFAULT,
  },
  progressThumb: {
    position: 'absolute',
    top: '50%',
    width: 14,
    height: 14,
    borderRadius: 7,
    marginLeft: -7,
    marginTop: -7,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: colors.primary.DEFAULT,
  },
  chapterMarker: {
    position: 'absolute',
    top: 0,
    width: 2,
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.55)',
    marginLeft: -1,
  },
  utilityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.xs,
  },
  utilityButton: {
    minHeight: 30,
    minWidth: 30,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(8, 12, 16, 0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
  },
  utilityLabel: {
    color: colors.text.inverse,
    fontFamily: typography.fontFamily.mono,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
  },
  menuWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: spacing.xs,
  },
  menuChip: {
    minHeight: 28,
    borderRadius: borderRadius.full,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.26)',
    backgroundColor: 'rgba(8, 12, 16, 0.6)',
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuChipActive: {
    borderColor: colors.primary.DEFAULT,
    backgroundColor: '#113447',
  },
  menuChipLabel: {
    color: colors.text.inverse,
    fontFamily: typography.fontFamily.mono,
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.medium,
  },
  menuChipLabelActive: {
    color: colors.primary.DEFAULT,
    fontWeight: typography.fontWeight.bold,
  },
});
